python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011G.svs /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011G.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011I.svs /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011J.svs /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011K.svs /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011K.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011L.svs /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011L.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012F.svs /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012F.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012I.svs /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012C.svs /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014F.svs /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014F.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014I.svs /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014L.svs /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014L.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0015/TMH0015G.svs /media/data_cifs/andreas/pathology/miriam/case0015/TMH0015G.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0015/TMH0015M.svs /media/data_cifs/andreas/pathology/miriam/case0015/TMH0015M.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
wait
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0017/TMH0017H.svs /media/data_cifs/andreas/pathology/miriam/case0017/TMH0017H.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0017/TMH0017K.svs /media/data_cifs/andreas/pathology/miriam/case0017/TMH0017K.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018B.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018C.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018E.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018E.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018F.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018F.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018G.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018G.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018J.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018K.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018K.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019B.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019C.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019F.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019F.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019G.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019G.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019H.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019H.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019I.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019J.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019K.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019K.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019L.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019L.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
wait
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020B.svs /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020A.svs /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020D.svs /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020D.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020E.svs /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020E.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023C.svs /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023E.svs /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023E.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023F.svs /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023F.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024D.svs /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024D.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024K.svs /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024K.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0025/TMH0025F.svs /media/data_cifs/andreas/pathology/miriam/case0025/TMH0025F.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0026/TMH0026J.svs /media/data_cifs/andreas/pathology/miriam/case0026/TMH0026J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027I.svs /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027L.svs /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027L.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0029/TMH0029L.svs /media/data_cifs/andreas/pathology/miriam/case0029/TMH0029L.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034D.svs /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034D.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034G.svs /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034G.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034I.svs /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034J.svs /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0035/TMH0035J.svs /media/data_cifs/andreas/pathology/miriam/case0035/TMH0035J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0041/TMH0041A.svs /media/data_cifs/andreas/pathology/miriam/case0041/TMH0041A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0041/TMH0041C.svs /media/data_cifs/andreas/pathology/miriam/case0041/TMH0041C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0041/TMH0041D.svs /media/data_cifs/andreas/pathology/miriam/case0041/TMH0041D.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0041/TMH0041E.svs /media/data_cifs/andreas/pathology/miriam/case0041/TMH0041E.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0043/TMH0043B.svs /media/data_cifs/andreas/pathology/miriam/case0043/TMH0043B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0043/TMH0043D.svs /media/data_cifs/andreas/pathology/miriam/case0043/TMH0043D.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0043/TMH0043F.svs /media/data_cifs/andreas/pathology/miriam/case0043/TMH0043F.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045C.svs /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045E.svs /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045E.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045F.svs /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045F.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045H.svs /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045H.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045K.svs /media/data_cifs/andreas/pathology/miriam/case0045/TMH0045K.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0062/TMH0062J.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0062/TMH0062J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0066/TMH0066C.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0066/TMH0066C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
wait
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068C-1.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068C-1.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068C-2.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068C-2.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068d-1.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068d-1.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068D-1.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068D-1.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068D-2.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068D-2.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068G-1.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068G-1.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068G-2.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068G-2.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068H.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068H.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068I.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068J-1.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068J-1.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068J-2.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068J-2.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068K-1.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068K-1.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068K-2.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068K-2.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068L-1.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068L-1.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068L-2.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0068/TMH0068L-2.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069B.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069C.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069D.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069D.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069F.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069F.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069G.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069G.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069H.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069H.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069I.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069J.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069L.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0069/TMH0069L.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070H.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070H.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070I.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070K.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070K.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070L.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070L.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070M-1.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070M-1.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070M-2.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070M-2.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070M-3.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070M-3.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070M-4.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0070/TMH0070M-4.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0071/TMH0071G.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0071/TMH0071G.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_tumor.py /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0071/TMH0071J.svs /media/data_cifs/andreas/pathology/more_miriam_cases/annotated_cases/TMH0071/TMH0071J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &












