python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023A.svs /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023B.svs /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023D.svs /media/data_cifs/andreas/pathology/miriam/case0023/TMH0023D.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024A.svs /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024B.svs /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024C.svs /media/data_cifs/andreas/pathology/miriam/case0024/TMH0024C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &  
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0025/TMH0025A.svs /media/data_cifs/andreas/pathology/miriam/case0025/TMH0025A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0025/TMH0025B.svs /media/data_cifs/andreas/pathology/miriam/case0025/TMH0025B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0025/TMH0025C.svs /media/data_cifs/andreas/pathology/miriam/case0025/TMH0025C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0026/TMH0026A.svs /media/data_cifs/andreas/pathology/miriam/case0026/TMH0026A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0026/TMH0026B.svs /media/data_cifs/andreas/pathology/miriam/case0026/TMH0026B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0026/TMH0026C.svs /media/data_cifs/andreas/pathology/miriam/case0026/TMH0026C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027A.svs /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027B.svs /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027C.svs /media/data_cifs/andreas/pathology/miriam/case0027/TMH0027C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
wait
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0029/TMH0029A.svs /media/data_cifs/andreas/pathology/miriam/case0029/TMH0029A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0029/TMH0029B.svs /media/data_cifs/andreas/pathology/miriam/case0029/TMH0029B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0029/TMH0029C.svs /media/data_cifs/andreas/pathology/miriam/case0029/TMH0029C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034A.svs /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034B.svs /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034C.svs /media/data_cifs/andreas/pathology/miriam/case0034/TMH0034C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &          
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020J.svs /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020J.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020L.svs /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020L.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020I.svs /media/data_cifs/andreas/pathology/miriam/case0020/TMH0020I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019D.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019D.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019E.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019E.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019A.svs /media/data_cifs/andreas/pathology/miriam/case0019/TMH0019A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018H.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018H.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018I.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018I.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018L.svs /media/data_cifs/andreas/pathology/miriam/case0018/TMH0018L.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
wait
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0017/TMH0017A.svs /media/data_cifs/andreas/pathology/miriam/case0017/TMH0017A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0017/TMH0017B.svs /media/data_cifs/andreas/pathology/miriam/case0017/TMH0017B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0015/TMH0015C.svs /media/data_cifs/andreas/pathology/miriam/case0015/TMH0015C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0015/TMH0015B.svs /media/data_cifs/andreas/pathology/miriam/case0015/TMH0015B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014C.svs /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014C.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014B.svs /media/data_cifs/andreas/pathology/miriam/case0014/TMH0014B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012A.svs /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012B.svs /media/data_cifs/andreas/pathology/miriam/case0012/TMH0012B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011A.svs /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011A.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches & 
python create_crops_normal.py /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011B.svs /media/data_cifs/andreas/pathology/miriam/case0011/TMH0011B.xml 0 /media/data_cifs/andreas/pathology/gleason_training_patches/all_patches &


